-- ORDER Table
CREATE TABLE `order` (
    ORDER_ID INT PRIMARY KEY
);
-- INV_TYPE Table
CREATE TABLE INV_TYPE (
    TY_GROUP VARCHAR(50) PRIMARY KEY
);
-- ORDER_ITEM Table
CREATE TABLE ORDER_ITEM (
    ORDER_ID INT NOT NULL,
    TY_GROUP VARCHAR(50) NOT NULL,
    O_LINE INT NOT NULL,
    PRIMARY KEY (ORDER_ID, TY_GROUP, O_LINE),
    FOREIGN KEY (ORDER_ID) REFERENCES `order`(ORDER_ID),
    FOREIGN KEY (TY_GROUP) REFERENCES INV_TYPE(TY_GROUP)
);
-- LOCATION Table
CREATE TABLE LOCATION (
    LOC_ID INT PRIMARY KEY
);
-- VENDOR Table
CREATE TABLE VENDOR (
    VEND_ID INT PRIMARY KEY
);
-- ITEM Table
CREATE TABLE ITEM (
    ITEM_ID INT PRIMARY KEY,
    VEND_ID INT NOT NULL,
    TY_GROUP VARCHAR(50) NOT NULL,
    FOREIGN KEY (VEND_ID) REFERENCES VENDOR(VEND_ID),
    FOREIGN KEY (TY_GROUP) REFERENCES INV_TYPE(TY_GROUP)
);
-- REPAIR Table
CREATE TABLE REPAIR (
    REP_ID INT PRIMARY KEY,
    ITEM_ID INT NOT NULL,
    FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ITEM_ID)
);
-- STORAGE Table
CREATE TABLE STORAGE (
    ITEM_ID INT NOT NULL,
    LOC_ID INT NOT NULL,
    PRIMARY KEY (ITEM_ID, LOC_ID),
    FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ITEM_ID),
    FOREIGN KEY (LOC_ID) REFERENCES LOCATION(LOC_ID)
);
-- USER Table
CREATE TABLE USER (
    USER_ID INT PRIMARY KEY
);

-- LAB_ASSISTANT Table
CREATE TABLE LAB_ASSISTANT (
    LA_ID INT PRIMARY KEY
);
-- LOG Table
CREATE TABLE LOG (
    LOG_DATE DATE NOT NULL,
    LOG_TIME TIME NOT NULL,
    LOG_READER INT NOT NULL,
    PRIMARY KEY (LOG_DATE, LOG_TIME, LOG_READER),
    FOREIGN KEY (LOG_READER) REFERENCES USER(USER_ID)
);

-- CHECK_OUT Table
CREATE TABLE CHECK_OUT (
    REP_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    ITEM_ID INT NOT NULL,
    PRIMARY KEY (REP_ID),
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID),
    FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ITEM_ID)
);
-- RESERVATION Table
CREATE TABLE RESERVATION (
    RES_ID INT PRIMARY KEY,
    USER_ID INT NOT NULL,
    LA_ID INT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID),
    FOREIGN KEY (LA_ID) REFERENCES LAB_ASSISTANT(LA_ID)
);
-- HOURS_WORKED Table
CREATE TABLE HOURS_WORKED (
    HW_SEMESTER VARCHAR(50) NOT NULL,
    LA_ID INT NOT NULL,
    HW_DATE DATE NOT NULL,
    PRIMARY KEY (HW_SEMESTER, LA_ID, HW_DATE),
    FOREIGN KEY (LA_ID) REFERENCES LAB_ASSISTANT(LA_ID)
);
-- WORK_SCHEDULE Table
CREATE TABLE WORK_SCHEDULE (
    SCHED_SEMESTER VARCHAR(50) NOT NULL,
    SCHED_WEEKDAY VARCHAR(50) NOT NULL,
    SCHED_IN TIME NOT NULL,
    SCHED_OUT TIME NOT NULL,
    LA_ID INT NOT NULL,
    PRIMARY KEY (SCHED_SEMESTER, SCHED_WEEKDAY, SCHED_IN, SCHED_OUT),
    FOREIGN KEY (LA_ID) REFERENCES LAB_ASSISTANT(LA_ID)
);
/*----------------------------------------------------------------------------------------------------------------------------------------------------*/
describe `order`;
describe INV_TYPE;
describe ORDER_ITEM;
describe LOCATION;
describe VENDOR;
describe ITEM;
describe REPAIR;
describe STORAGE;
describe USER;
describe LAB_ASSISTANT;
describe LOG;
describe CHECK_OUT;
describe RESERVATION;
describe HOURS_WORKED;
describe WORK_SCHEDULE;